### PR TITLE
[fixbug] The revision of version number: 6f6f9ec will invalidate the Watch interface.

### PR DESCRIPTION
**Pull request by fananchong**

### CODE REVIEW

**Comment by asim** [comment]
Can you explain this PR please

**Comment by fananchong** [comment]
micro/mdns v0.1.0 ,  mdns_watcher_test.go pass
micro/mdns v0.2.0 ,  mdns_watcher_test.go fail,  block in  w.Next() , Obviously, the signal is not received.
So I compared the history and found that there is a problem with this version of 6f6f9ec.

**Comment by asim** [comment]
Which tests do you mean? The tests pass everywhere for me, in this repo and in go-micro.

**Comment by fananchong** [comment]
https://github.com/micro/go-micro/blob/master/registry/watcher_test.go

**Comment by asim** [comment]
This test passes for me and passes on travis. Is the issue not related to your own environment? Hence the port PR?

**Comment by fananchong** [comment]
Indeed, I have no problem testing under Linux, there will be this problem under window 10.

**Pull request merged**
